# Funding platforms for sponsors

# GitHub Sponsors
github: kah3vich

# Patreon
# patreon: USERNAME

# Open Collective
open_collective: kah3vich

# Buy Me a Coffee
# buy_me_a_coffee: USERNAME

# Custom funding URLs
# custom:
#   - URL

